apiVersion: v1
kind: Secret
metadata:
  name: orders-html5-deployer-secret
  labels:
    app: orders-html5-deployer
stringData:
  EXIT_PROCESS_AFTER_UPLOAD: "true"
  PORT: "5000"
  SAP_CLOUD_SERVICE: "cap.orders.kyma.service"
  SUBACCOUNT_LEVEL_DESTINATION: "true"
  BACKEND_DESTINATIONS: "[{
    \"Name\":\"cap-orders-kyma-srv-<your-namespace>\",
    \"Description\":\"cap orders kyma application\",
    \"Type\":\"HTTP\",
    \"ProxyType\":\"Internet\",
    \"tokenServiceURLType\": \"Dedicated\",
    \"Authentication\":\"OAuth2UserTokenExchange\",
    \"HTML5.DynamicDestination\": true,
    \"clientId\": \"<xsuaa-clientid>\",
    \"clientSecret\":\"<xsuaa-clientsecret>\",
    \"tokenServiceURL\": \"<xsuaa-url>/oauth/token\",
    \"URL\":\"https://cap-orders-service-<your-namespace>.<cluster domain>\"}]"