apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-orders-service 
  labels:
    app: cap-orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cap-orders-service
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: cap-orders-service  
    spec:     # pod spec                  
      containers: 
      - image: {your-docker-account}/cap-orders-service:latest # image we pushed
        name: cap-orders-service 
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 4004
        envFrom:
          - secretRef:
              name: orders-vcap-services
---
apiVersion: v1
kind: Service
metadata:
  name: cap-orders-service
  labels:
    app: cap-orders-service
spec:
  ports:
  - name: http
    port: 4004
    targetPort: 4004
  selector:
    app: cap-orders-service
---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: cap-orders-service
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - config: {}
      handler: noop
    methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - HEAD
    path: /.*
  service:
    host: cap-orders-service-{your-namespace}
    name: cap-orders-service
    port: 4004